// Generated by CoffeeScript 1.8.0
(function() {
  var Assignement, AssignementPart, DemoAssignements, DemoStundents, Grade, GradeBookViewModel, Student;

  Student = (function() {
    function Student(data) {
      this.id = ko.observable(data.id);
      this.name = ko.observable(data.name);
      this.lastname = ko.observable(data.lastname);
      this.comments = ko.observable(data.comments);
      this.grades = ko.observableArray([]);
      this.final_grade = ko.computed(function() {
        return 10;
      }, this);
    }

    Student.prototype.initialize_grades = function(assignments) {
      var assignment, part, _i, _j, _len, _len1, _ref;
      for (_i = 0, _len = assignments.length; _i < _len; _i++) {
        assignment = assignments[_i];
        _ref = assignment.parts();
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          part = _ref[_j];
          this.grades.push(new Grade(part));
        }
      }
      return this;
    };

    return Student;

  })();

  Grade = (function() {
    function Grade(assignment) {
      this.grade = ko.observable();
      this.text_grade = ko.observable();
      this.assignment = assignment;
      this.wieghted_grade = ko.computed(function() {
        return 10;
      }, this);
    }

    return Grade;

  })();

  Assignement = (function() {
    function Assignement(data) {
      this.title = ko.observable();
      this.type = ko.observable();
      this.weight = ko.observable();
      this.due_date = ko.observable();
      this.parts = ko.observableArray();
      this.multiple = ko.computed(function() {
        return this.parts().length > 1;
      }, this);
      this.is_selected = ko.computed(function() {
        if (this.multiple) {
          return false;
        } else {
          if (this.parts().length > 0) {
            return this.parts()[0].is_selected();
          } else {
            return false;
          }
        }
      }, this);
    }

    Assignement.prototype.initialize_data = function(data) {
      this.title(data.title);
      this.type(data.type);
      this.weight(data.weight);
      this.due_date(data.due_date);
      this.parts(data.parts);
      return this;
    };

    return Assignement;

  })();

  AssignementPart = (function() {
    function AssignementPart(data) {
      this.due_date = ko.observable(data.due_date);
      this.weight = ko.observable(data.weight);
      this.title = ko.observable(data.title);
      this.is_selected = ko.observable(false);
    }

    AssignementPart.prototype.toggle_selection = function() {
      return this.is_selected(!this.is_selected());
    };

    return AssignementPart;

  })();

  DemoAssignements = function() {
    var a;
    a = [
      new Assignement().initialize_data({
        title: "TP1",
        type: "Trabajo Practico",
        weight: "50",
        parts: [
          new AssignementPart({
            title: "Preguntas",
            weight: "50",
            due_date: "12/09"
          }), new AssignementPart({
            title: "Participacion",
            type: "Part",
            weight: "50",
            due_date: "20/09"
          })
        ]
      }), new Assignement().initialize_data({
        title: "TP5",
        type: "Trabajo Practico",
        weight: "10",
        due_date: "30/6",
        parts: [
          new AssignementPart({
            title: "",
            weight: "100",
            due_date: "12/09"
          })
        ]
      }), new Assignement().initialize_data({
        title: "TP3",
        type: "Trabajo Practico",
        weight: "10",
        due_date: "30/6",
        parts: [
          new AssignementPart({
            title: "",
            weight: "100",
            due_date: "12/09"
          })
        ]
      }), new Assignement().initialize_data({
        title: "TP3",
        type: "Trabajo Practico",
        weight: "10",
        due_date: "30/6",
        parts: [
          new AssignementPart({
            title: "",
            weight: "100",
            due_date: "12/09"
          })
        ]
      })
    ];
    return a;
  };

  DemoStundents = function(a) {
    var s;
    s = [
      new Student({
        id: 12223,
        name: "Julia",
        lastname: "Lasarte",
        comments: "Un comentario"
      }).initialize_grades(a), new Student({
        id: 465416,
        name: "Juan",
        lastname: "Lasarte",
        comments: ""
      }).initialize_grades(a), new Student({
        id: 45646,
        name: "Pedro",
        lastname: "Lasarte",
        comments: ""
      }).initialize_grades(a), new Student({
        id: 13213,
        name: "Maria",
        lastname: "Lasarte",
        comments: ""
      }).initialize_grades(a), new Student({
        id: 45646,
        name: "Elena",
        lastname: "Lasarte",
        comments: "Un comentario"
      }).initialize_grades(a), new Student({
        id: 79878,
        name: "Pedro",
        lastname: "Lasarte",
        comments: "Un comentario"
      }).initialize_grades(a)
    ];
    return s;
  };

  GradeBookViewModel = (function() {
    function GradeBookViewModel() {
      this.assignements = ko.observableArray(DemoAssignements());
      this.students = ko.observableArray(DemoStundents(this.assignements()));
    }

    GradeBookViewModel.prototype.breakpoint = function() {
      return console.log("breaking point");
    };

    GradeBookViewModel.prototype.convert_selected_assignments_to_group = function() {
      var a, assignment, _i, _len, _ref, _results;
      assignment = new Assignement();
      _ref = this.assignements();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        a = _ref[_i];
        if (a.is_selected()) {
          _results.push(console.log(a));
        }
      }
      return _results;
    };

    return GradeBookViewModel;

  })();

  ko.applyBindings(new GradeBookViewModel());

}).call(this);
