// Generated by CoffeeScript 1.8.0
(function() {
  var Assignement, AssignementPart, DemoAssignements, DemoStundents, Grade, GradeBookViewModel, Student;

  Student = (function() {
    function Student(data) {
      this.id = ko.observable(data.id);
      this.name = ko.observable(data.name);
      this.lastname = ko.observable(data.lastname);
      this.comments = ko.observable(data.comments);
      this.grades = ko.observableArray([]);
      this.final_grade = ko.computed(function() {
        return 10;
      }, this);
    }

    Student.prototype.initialize_grades = function(assignments) {
      var assignment, part, _i, _j, _len, _len1, _ref;
      for (_i = 0, _len = assignments.length; _i < _len; _i++) {
        assignment = assignments[_i];
        _ref = assignment.parts();
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          part = _ref[_j];
          this.grades.push(new Grade(part));
        }
      }
      return this;
    };

    return Student;

  })();

  Grade = (function() {
    function Grade(assignment) {
      this.grade = ko.observable();
      this.text_grade = ko.observable();
      this.assignment = assignment;
      this.wieghted_grade = ko.computed(function() {
        return 10;
      }, this);
    }

    return Grade;

  })();

  Assignement = (function() {
    function Assignement(data) {
      this.title = ko.observable(data.title);
      this.type = ko.observable(data.type);
      this.weight = ko.observable(data.weight);
      this.due_date = ko.observable(data.due_date);
      this.parts = ko.observableArray(data.parts);
      this.multiple = this.parts().length > 1;
    }

    return Assignement;

  })();

  AssignementPart = (function() {
    function AssignementPart(data) {
      this.due_date = ko.observable(data.due_date);
      this.weight = ko.observable(data.weight);
      this.title = ko.observable(data.title);
    }

    return AssignementPart;

  })();

  DemoAssignements = function() {
    var a;
    a = [
      new Assignement({
        title: "TP1",
        type: "Trabajo Practico",
        weight: "50",
        parts: [
          new AssignementPart({
            title: "Preguntas",
            weight: "50",
            due_date: "12/09"
          }), new AssignementPart({
            title: "Participacion",
            type: "Part",
            weight: "50",
            due_date: "20/09"
          })
        ]
      }), new Assignement({
        title: "TP5",
        type: "Trabajo Practico",
        weight: "10",
        due_date: "30/6",
        parts: [
          new AssignementPart({
            title: "",
            weight: "100",
            due_date: "12/09"
          })
        ]
      }), new Assignement({
        title: "TP3",
        type: "Trabajo Practico",
        weight: "10",
        due_date: "30/6",
        parts: [
          new AssignementPart({
            title: "",
            weight: "100",
            due_date: "12/09"
          })
        ]
      }), new Assignement({
        title: "TP3",
        type: "Trabajo Practico",
        weight: "10",
        due_date: "30/6",
        parts: [
          new AssignementPart({
            title: "",
            weight: "100",
            due_date: "12/09"
          })
        ]
      })
    ];
    return a;
  };

  DemoStundents = function(a) {
    var s;
    s = [
      new Student({
        id: 12223,
        name: "Julia",
        lastname: "Lasarte",
        comments: "Un comentario"
      }).initialize_grades(a), new Student({
        id: 465416,
        name: "Juan",
        lastname: "Lasarte",
        comments: ""
      }).initialize_grades(a), new Student({
        id: 45646,
        name: "Pedro",
        lastname: "Lasarte",
        comments: ""
      }).initialize_grades(a), new Student({
        id: 13213,
        name: "Maria",
        lastname: "Lasarte",
        comments: ""
      }).initialize_grades(a), new Student({
        id: 45646,
        name: "Elena",
        lastname: "Lasarte",
        comments: "Un comentario"
      }).initialize_grades(a), new Student({
        id: 79878,
        name: "Pedro",
        lastname: "Lasarte",
        comments: "Un comentario"
      }).initialize_grades(a)
    ];
    return s;
  };

  GradeBookViewModel = function() {
    var self;
    self = this;
    self.assignements = ko.observableArray(DemoAssignements());
    self.students = ko.observableArray(DemoStundents(self.assignements()));
    self.breakpoint = function() {
      console.log("breaking point");
    };
  };

  ko.applyBindings(new GradeBookViewModel());

}).call(this);
